Add preproc options and input arguments

diff --git a/FeMIP b/FeMIP
--- a/FeMIP
+++ b/FeMIP
@@ -9,28 +9,62 @@
 # 
 # FeMIP requires the user to specify the file(s) to be processed as well as the vertical grid of choice
 #
-# Written by Jonathan J Rogerson
-# 25 February 2020
-# Edited 5 December 2020
+# Author: Jonathan J Rogerson (UCT)
+# Contributor(s): M. Vichi (UCT)
 
-MYGRID=false          # Set MYGRID to true if you wish to use your custom grid created by 'makegrid'
-INDIR="../MODEL_DATA" # Directory of model files to be processed
-EXDIR="../OUTPUTS" # Location where output directory will be created
-OUTDIR="$EXDIR/FeMIP_01_nearest_interpolation" # Output directory
+# Default options
+MYGRID=false          	# Set MYGRID to true if you wish to use your custom grid created by 'makegrid'
+INDIR="../MODEL_DATA" 	# Directory of model files to be processed
+EXDIR="../OUTPUTS" 	# Root Output directory
+PREFIX=""		# Name used for the output directory and appended to the files
+USAGE="Usage: cmd [-g GRIDFILE] [-i INDIR] [-o OUTDIR] [-p PREFIX] FILELIST "
 
+if [[ "$#" == 0 ]]
+then
+   echo "$USAGE"
+   exit 1
+fi
+
+while getopts "giop:" opt; do
+  case ${opt} in
+      g ) MYGRID=true 
+	  mygridfile=$OPTARG ;;
+      i ) INDIR=$OPTARG 
+          echo "The input dir = $INDIR" ;;
+      o ) EXDIR=$OPTARG ;;
+      p ) PREFIX=$OPTARG
+          echo "The prefix = $PREFIX" ;;
+      \?) echo "$USAGE"
+          exit 1;;
+  esac
+done
+shift $(( OPTIND - 1 )) 
+
+if [[ ! -d $EXDIR ]]
+then
+   echo "The directory ${EXDIR} does not exist. Creating it..."
+   mkdir $EXDIR
+fi
+
+if [[ ! -d $INDIR ]]
+then
+   echo "The directory ${INDIR} does not exist. Please use option -i INDIR."
+   exit 1
+fi
+
+OUTDIR=$EXDIR/$PREFIX
+if [[ ! -d $OUTDIR ]]
+then
+   mkdir $OUTDIR    # Create directory where processed files will go
+fi
 cd $INDIR
-FILES=`ls UKSEM.nc`            # Specify the file(s) to be processed
 
-##############################
-#	END USER INPUTS
-##############################
 LONLAT="-180,180,-90,90"
 GRID="r360x180"
-TEMPLATE="template_FeMIP_01"
-mkdir $OUTDIR	         	# Create directory where processed files will go
-# Create a once-off horizontal gridding template
+TEMPLATE="template_FeMIP_01.nc"
 
-cdo -f nc -sellonlatbox,$LONLAT -random,$GRID $TEMPLATE.nc
+# Create a once-off horizontal gridding template
+cdo -f nc -sellonlatbox,$LONLAT -random,$GRID $TEMPLATE
 
 if [ "$MYGRID" = true ] ; then
 
@@ -39,7 +73,7 @@ if [ "$MYGRID" = true ] ; then
   read line < depth
   numbers=($line)
   LEVELS="$numbers"
-  cp ./mygrid $OUTDIR/
+  cp ./$mygridfile $OUTDIR/
   chmod 755 mygrid
 
 else
@@ -58,10 +92,10 @@ EOR
 
 fi
   
-for f in $FILES
+for f in "$@"
 do
   echo $f
-  cdo -f nc remapnn,$TEMPLATE.nc -intlevel,$LEVELS $f $OUTDIR/$f
+  cdo -f nc remapnn,$TEMPLATE -intlevel,$LEVELS $f $OUTDIR/$f
   if [ "$MYGRID" = true ] ; then
     cdo -f nc setzaxis,mygrid $OUTDIR/$f $OUTDIR/FeMIP_$f           # Loop over the file(s) and do the interpolation
     mv $INDIR/levels $OUTDIR/
@@ -71,6 +105,8 @@ do
   rm $OUTDIR/$f
 done
 
-echo "ALL done"
+# cleanup
+rm WOA01 $TEMPLATE
+echo "FeMIP processing completed"
 
 
